apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
spec:
  secretName: tls-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - Suvanjan Homelab
  dnsNames:
    - keycloak-service
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
