apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expenses
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/smukherj1/k8s-home.git
    targetRevision: main
    path: applications/expenses
  destination:
    server: "https://kubernetes.default.svc"
    namespace: expenses
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  revisionHistoryLimit: 2
