apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: immich
      repoURL: oci://ghcr.io/immich-app/immich-charts/
      targetRevision: 0.10.1
      helm:
        releaseName: immich
        valueFiles:
          - $values/applications/immich/helm/values.yml
    - repoURL: https://github.com/smukherj1/k8s-home.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/smukherj1/k8s-home.git
      targetRevision: main
      path: applications/immich
  destination:
    server: "https://kubernetes.default.svc"
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
