---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-web
  namespace: pihole
spec:
  defaultBackend:
    service:
      name: pihole-web
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - pihole-web
