ingress:
  enabled: false

serviceDhcp:
  enabled: false

serviceDns:
  type: LoadBalancer
  loadBalancerClass: "tailscale"
  
admin:
  enabled: true
  existingSecret: "admin-creds"
  passwordKey: "password"

# Ads providers to block
adlists:
- https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts