---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp
  namespace: headlamp
spec:
  defaultBackend:
    service:
      name: headlamp
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - headlamp
