type: postgresql

version:
  postgresql: "17"

cluster:
  instances: 1
  # https://github.com/tensorchord/cloudnative-vectorchord/pkgs/container/cloudnative-vectorchord
  # Immich v2.0.0 only supports Vectorchord >=0.3 <0.5
  imageName: "ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.4.3"
  storage:
    size: 10Gi
    storageClass: "local-path"

  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 4Gi

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  initdb:
    postInitSQL:
      - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
