apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
