apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: token
  serviceAccountName: suvanjan-homelab
  volumes:
    - name: token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 600
              audience: suvanjan-homelab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: suvanjan-homelab
