---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelab
spec:
  defaultBackend:
    service:
      name: minter
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - homelab
---
apiVersion: v1
kind: Service
metadata:
  name: minter
spec:
  selector:
    app.kubernetes.io/name: minter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minter-deployment
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: minter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minter
    spec:
      containers:
      - name: minter
        image: ghcr.io/smukherj1/homelab-depot/minter:main
        ports:
        - containerPort: 8080
        serviceAccountName: cluster-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cluster-admin